### PR TITLE
update langspec

### PR DESCRIPTION
**Pull request by shiqizng**
Regenerate langspec.json to include latest TealV4 opcodes.

### CODE REVIEW

**Review by jdtzmn — APPROVED** [review]
Looks good, but not sure I'm qualified to review the `langspec.json` files.

**Review by jannotti — APPROVED** [review]
Seems good.  In the future, we should consider whether Go's new https://golang.org/pkg/embed/
would let us get rid of that bundledSpecInject.go thing.  It looks like we're just trying to compile the bytes into the program, which is what that embed system does in Go 1.16

**Review by jdtzmn — APPROVED** [review]
Looks good! I don't know enough about the `logic/bundledSpecInject.go` file, but I assumed it should have changes. Is my assumption incorrect? Or are there missing changes?

**Review by jannotti — APPROVED** [review]

**Review by jdtzmn — APPROVED** [review]

**Comment by jasonpaulos** [comment]
@shiqizng have you regenerated the `bundledSpecInject.go` file with the latest langspec change? Other than that, this looks good!

**Review by jasonpaulos — APPROVED** [review]

**Comment by jasonpaulos** [comment]
Pending tests, feel free to merge

**Pull request merged**
