### PR TITLE
Update Travis Environment Variables

### PR DESCRIPTION
**Pull request by algobarb**
## Summary
Due to a Travis security issue recently, we'll be rotating and re-encrypting Travis variables.

## Test
Making sure Travis passes with the new variables.

### CODE REVIEW

**Comment by algojack** [comment]
are the encrypted values really necessary? or is there a better way like env vars or pulling from a secret store? (not sure how we handle secrets in a public repo like this without allowing anyone to use them, but i think there might be a better way).

**Comment by algobarb** [comment]
I moved the environment values from travis yml file and into the Travis Project settings instead.

**Review by algojack — APPROVED** [review]
lgtm

**Comment by algobarb** [comment]
For some reason travis mixed up this PR with the forked pr test I had.. so I'll recreate this PR.

**Pull request closed without merging**
