### PR TITLE
Update TEAL langspec.json for TEAL v2

### PR DESCRIPTION
**Pull request by pzbitskiy**

### CODE REVIEW

**Comment by winder** [comment]
@EvanJRichard I'm not sure why there's a conflict, could you take a look?

**Comment by EvanJRichard** [comment]
@winder I _think_ we need to force-merge taking `ours` or `theirs`, but I'm not sure which one is correct. @pzbitskiy / @algorandskiy What do you think?

**Comment by algorandskiy** [comment]
Langspec in this PR is already stalled. I'll update the PR later today with the latest and greatest stuff. `logic/bundledSpecInject.go` is a generated file from `langspec.json`.

**Comment by algorandskiy** [comment]
replaced by #163

**Pull request closed without merging**
