### PR TITLE
feat: add min-balance to account information model

### PR DESCRIPTION
**Pull request by kieranroneill**
## Summary

Simply exposes the `min-balance` in the [`Account`](https://github.com/algorand/go-algorand-sdk/blob/develop/client/v2/common/models/account.go) model as defined in the REST API [response](https://developer.algorand.org/docs/rest-apis/algod/#account).

As the API defines the `min-balance` as required, there should always be a value. As of now (19th January 2024), minimum balance should always be >= 100,000 microAlgos.

Closes [#272](https://github.com/algorand/go-algorand-sdk/issues/272).

### CODE REVIEW

**Comment by gmalouf** [comment]
@kieranroneill thanks for contributing, can you try rebasing this to give it another go?

**Comment by kieranroneill** [comment]
> @kieranroneill thanks for contributing, can you try rebasing this to give it another go?

Hey @gmalouf I have updated the PR with the latest version :)

**Comment by gmalouf** [comment]
I jusr realized that the Account struct is actually generated based on the [specification file in indexer](https://github.com/algorand/indexer/blob/main/api/indexer.oas2.json) using the [sdk codegen
](https://github.com/algorand/generator/tree/master/.github/actions/sdk-codegen) action that runs on this repository.

There is a draft PR open to add this: https://github.com/algorand/indexer/pull/1596, I'm looking into what tests need to go in before moving forward.

**Comment by gmalouf** [comment]
#641 was just merged that addresses this (now that https://github.com/algorand/indexer/pull/1596) was merged

**Pull request closed without merging**
