### PR TITLE
Updates  FromBase64String() to correctly return the signed transaction

### PR DESCRIPTION
**Pull request by king-iron**
Fix for https://github.com/algorand/go-algorand-sdk/issues/224

### CODE REVIEW

**Comment by winder** [comment]
Thanks, you're right this doesn't work at all...

There's a simpler solution though, this should work if you make the receiver a pointer
```diff
-func (signedTxn SignedTxn) FromBase64String(b64string string) error {
+func (signedTxn *SignedTxn) FromBase64String(b64string string) error {
```

Looks like block needs this also...
```diff
-func (block Block) FromBase64String(b64string string) error {
+func (block *Block) FromBase64String(b64string string) error {
```

Would you be able to update these and make a small unit test?

**Comment by king-iron** [comment]
Thanks @winder! Using a receiver pointer makes a lot more sense. 

I am having trouble with the unit test. Specifically, where to place it in the code base and then how to run the unit test from the makefile?

**Comment by winder** [comment]
It looks like we don't have tests for this file, so you would make one named `basics_test.go`

It would look something like:
```
package types

import (
	"testing"

	"github.com/stretchr/testify/require"
)

func TestSignedTxnFromBase64String() {

}

func TestBlockFromBase64String() {

}
```

You can put a target like this in the Makefile, the existing `make unit` pulls in some integration tests that you shouldn't have to worry about for this:
```
test:    
  go test $(TEST_SOURCES_NO_CUCUMBER)
```

**Comment by king-iron** [comment]
Thank you! I added a unit test in.

**Comment by winder** [comment]
@king-iron thanks for the contribution!

**Pull request merged**
